services:
  appDb:
    image: mysql:latest
    container_name: appDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: appDb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - appDb:/var/lib/mysql
  php:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
 
volumes:
  appDb: