services:
  appDb:
    image: mysql:latest
    container_name: appDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: appDb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - appDb:/var/lib/mysql

volumes:
  appDb: